import { MatchReader } from './MatchReader';
import { CsvFileReader } from './CsvFileReader';
import { Summery } from './Summery';
import { ConsoleReport } from './reportTargets/ConsoleReport';
import { WinsAnalysis } from './analyzers/WinsAnalysis';
let csvFileReader = new CsvFileReader('football.csv');
let matchReader = new MatchReader(csvFileReader);
matchReader.load();
const summery = new Summery(new WinsAnalysis('Man United'), new ConsoleReport());
summery.buildAndPrintReport(matchReader.matches);
